# cmd: conda build . -c conda-forge
package:
    name: thermp
    version: "0.6.0"

source:
    path: .

requirements:
    build:
        - conda-forge::cmake=3.20.2
        - conda-forge::gfortran_linux-64=7.5.0
